### ISSUE TITLE
source.unsplash.com does not work anymore - replace it with individual folder?

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/unsplash#137] opened 2024-07-19 07:47 UTC
source.unsplash.com does not work anymore. Apparently there is now an API that requires access data. 

I suggest that you remove the entire Unsplash components and load the backgrounds from a list of your own images. This can be done with very little HTML and JavaScript code. In addition, the Splash app then requires very little maintenance.

example code:
```
<?php
$dir = __DIR__;
$images = glob($dir . "/*.{jpg,jpeg,png,gif}", GLOB_BRACE);
if (count($images) > 0) {
    $randomImage = $images[array_rand($images)];
    echo "<html><body>";
    echo "<img src='" . basename($randomImage) . "' alt='random image' style='max-width: 100%; height: auto;'>";
    echo "</body></html>";
} else {
    echo "No image found.";
}
?>
```

**Comment by newhinton** [comment] 2024-07-19 07:51
The issue-template exists for a reason. This is a duplicate of multiple tickets.

**Closed as completed by newhinton** 2024-07-19 07:51 UTC
Labels: bug, duplicate, didnt-follow-template
