### ISSUE TITLE
Picture background used for navigation bar, even if "use pic for nav bar" is deactivated -> readability issue

### ISSUE THREAD

**Issue by chrisbley** [nextcloud/unsplash#92] opened 2022-04-09 11:44 UTC
![image](https://user-images.githubusercontent.com/97885880/162572649-df29d61d-5d83-4902-adfd-43bcba1aee65.png)
![image](https://user-images.githubusercontent.com/97885880/162572692-18d4aef0-5c1e-4a63-bcf1-123d61471fe1.png)

checkbox in Administration / Design not doing what it's supposed to do: keep the nav bar free from pic

**Comment by newhinton** [comment] 2022-04-09 12:26
Which version of nextcloud and splash are you using?

**Comment by chrisbley** [comment] 2022-04-09 12:38
I'm using linuxserver/nextcloud:23.0.3-php8 with Splash 1.2.4

**Comment by newhinton** [comment] 2022-04-09 12:40
hm, i can't reproduce that. Have you tried flushing the cache? Or using a different browser?

**Comment by chrisbley** [comment] 2022-04-09 14:41
thanks for looking into it! yes, flushing the cache doesn't help, same result on brave and edge browsers.

**Comment by newhinton** [comment] 2022-04-11 08:31
Do you have the custom-css app activated? Your bar seems strange, why is it so big?

**Comment by newhinton** [comment] 2022-04-12 13:59
Is that your dashboard?

**Comment by chrisbley** [comment] 2022-04-12 16:20
No custom css app, but I used the margin 0px work around on dashboard.css since my post.
Yes, this was my dashboard.

Mit freundlichen Grüßen | Best regards

Christoph Bley
Diplom-Tonmeister HfM Detmold

---

Christoph Bley
Freilandstr. 6
82178 Puchheim

+49 179 5629366
***@***.***
www.christophbley.com
Am 12. Apr. 2022, 15:59 +0200 schrieb Felix Nüsse ***@***.***>:

**Comment by newhinton** [comment] 2022-04-12 17:27
In that case it is working as intended. There is a seperate switch, the third one in your screenshot, that controls the dasboard background.

**Comment by newhinton** [comment] 2022-04-12 17:43
No, the navigation bar in the dashboard has a transparency applied so that the default blue cloud will be fully visible. That is intended by the nextcloud design team, and it works with most pictures, and nextcloud ships with some images that work well. 

And the splash app follows this logic. We just replace the background image, but do not edit the transparency of the navigation bar .

You can use this with either the custom css app (easy, does not break updates) or edit the dashboard.css-file in the unsplash directory directly (does break updates, i think.)

```
#header {
  background: var(--color-primary-element) !important;
}
```

This block of code will reintroduce the main color in every navigation bar , including the dashboard.

I am not sure if we really need to introduce another setting, since the default dashboard image provides a clear readability.
I will close this for now, but we may revisit this if more users have objections or a need for this.

**Closed by newhinton** 2022-04-12 17:43 UTC

**Comment by chrisbley** [comment] 2022-04-12 17:47
Understood, thank you very much!
