### ISSUE TITLE
[Bug]: Login Page not reachable due error (if logged in NC works without problem)

### ISSUE THREAD

**Issue by sirdrakeistda** [nextcloud/unsplash#141] opened 2024-09-02 09:21 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

A new login is not possible because the login page is not reachable. If you are still logged in, using nextclopud does work without any problem. If you try to reach the login page in a privat browser window (not logged in), I get following error:
```
 Error Call to undefined method OCP\AppFramework\Http\Events\BeforeLoginTemplateRenderedEvent::isLoggedIn()
    /var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.phpZeile 86
    OCA\Unsplash\EventListener\BeforeTemplateRenderedEventListener->handle()
    /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.phpZeile 230
    OC\EventDispatcher\ServiceEventListener->__invoke()
    /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.phpZeile 59
    Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
    /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.phpZeile 86
    Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
    /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.phpZeile 98
    OC\EventDispatcher\EventDispatcher->dispatch()
    /var/www/nextcloud/lib/private/AppFramework/Middleware/AdditionalScriptsMiddleware.phpZeile 50
    OC\EventDispatcher\EventDispatcher->dispatchTyped()
    /var/www/nextcloud/lib/private/AppFramework/Middleware/MiddlewareDispatcher.phpZeile 142
    OC\AppFramework\Middleware\AdditionalScriptsMiddleware->afterController()
    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.phpZeile 176
    OC\AppFramework\Middleware\MiddlewareDispatcher->afterController()
    /var/www/nextcloud/lib/private/AppFramework/App.phpZeile 184
    OC\AppFramework\Http\Dispatcher->dispatch()
    /var/www/nextcloud/lib/private/Route/Router.phpZeile 338
    OC\AppFramework\App::main()
    /var/www/nextcloud/lib/base.phpZeile 1053
    OC\Route\Router->match()
    /var/www/nextcloud/index.phpZeile 49
    OC::handleRequest()
```
Interestingly is the login page reachable using this link: https://nextcloud.example/index.php/login?redirect_url=/index.php/settings/integrity/failed , but the login still does not work. Not sure if it is related, but my nextcloud instance is also affected by this bug: https://github.com/nextcloud/server/issues/47359 

### Steps to reproduce

1. Update Nextcloud to 29.0.5
2. try a privat browser window (you are not logged in in this window)
3. see error message

### Expected behavior

login should work and login page should be reachable

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 28.0.1 to 28.0.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kesselb** [comment] 2024-09-02 11:56
I haven't tested it, but assume that https://github.com/nextcloud/unsplash/blob/b76a38e3466631f69d432f7994679dfd008cef61/lib/EventListener/BeforeTemplateRenderedEventListener.php#L82-L86 only works with BeforeTemplateRenderedEvent but not BeforeLoginTemplateRenderedEvent

**Comment by kesselb** [comment] 2024-09-02 11:58
Duplicate of https://github.com/nextcloud/unsplash/issues/139

**Comment by newhinton** [comment] 2024-09-02 11:59
This is a known issue, with a fix already in the works.
However, unsplash should not be enabled after the update to 29, did you enable it by force?

@kesselb Is my assumption wrong that unsupported apps get disabled?

**Comment by kesselb** [comment] 2024-09-02 12:03
> Is my assumption wrong that unsupported apps get disabled?

Users can force enable apps  (config.php, app_install_overwrite)

**Comment by newhinton** [comment] 2024-09-02 12:05
ah okay. Generally speaking i wanted to know if i had done anything wrong in the app declaration which made it possible to "just" install the app, without forcing anything. In this case i am good :D

**Comment by Manuel1948** [comment] 2024-09-03 10:52
> This is a known issue, with a fix already in the works. However, unsplash should not be enabled after the update to 29, did you enable it by force?
> 
> @kesselb Is my assumption wrong that unsupported apps get disabled?

We had the same problem, but as I understand the app should have been disabled when upgrading to Nextcloud 29 (except if someone has forced it to install) or did I missunderstand something? We didn't have it forced but also ran into this problem. 

Should this app be visible in the App-Store if it is not compatible?

**Comment by Manuel1948** [comment] 2024-09-03 11:02
> This is a known issue, with a fix already in the works. However, unsplash should not be enabled after the update to 29, did you enable it by force?
> 
> @kesselb Is my assumption wrong that unsupported apps get disabled?

We had the same problem but also didn't have forced an app and as I udnerstand this app should have been disabled automatically when updating to NC 29 or did I misunderstand something?

Another question, why is this called Unsplashed when the App is named Splash? For me this lead to misunderstandings and I had to rewrite my answer three times.

**Comment by newhinton** [comment] 2024-09-03 11:12
Because originally the apl was called unsplash. However, since we dont wanted to create copyright/branding issues, we changed it where it is visible to the user. 

The "technical" side was never changed.

**Closed** 2024-09-05 10:23 UTC
Labels: bug
