### ISSUE TITLE
Splash - not supported on Nextcloud 28

### ISSUE THREAD

**Issue by Danielson89** [nextcloud/unsplash#131] opened 2023-11-15 08:50 UTC
use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

- [ ] This is not a feature request
- [ ] This is not an image-provider request
- [ ] I have searched the issuetracker if the issue is not already reported.

**Describe the bug:**
I believe the 2.2.1 isn't supported on NextCloud 28

**To Reproduce:**
It's not displaying the images at the login as it normally would

**Expected behavior:**
Not showing on the login screen,  attempted to remove app and reinstall app,  rebooted services, server etc

**Screenshots:**
Screenshot will show the app successfully installed and no background photo

**Server:**
 - Nextcloud version:  28
 - Splash-App version: 2.2.1

**Additional Information:**
It's such a cool app,  hope to get it working again
Thanks
Daniel - Perth Western Australia.

**Comment by Raemsna** [comment] 2023-12-02 10:18
maybe related to #123 ?

**Comment by TakeshiTurk** [comment] 2023-12-18 20:39
Not related @Raemsna. Issue is settings page does not work.

![resim](https://github.com/nextcloud/unsplash/assets/153630289/2203a99a-20cb-4faa-97ab-3977259af11e)

**Comment by newhinton** [comment] 2023-12-19 17:35
I am currently working on an update for Splash. I already fixed the bug you found, but there is still a bit more to do. I hope to be done before christmas!

**Comment by ste7enm** [comment] 2024-01-02 20:20
> Not related @Raemsna. Issue is settings page does not work.

Perhaps related to this and the fix, I'm in NextCloud 28.0.1 and have enabled Splash. It works, but no modifications made in the settings (under Theming) save. It claims that it's saved, but then you refresh and everything has reset to default settings. Other changes made under Theming to non-Splash settings are saved correctly.

![Changes](https://github.com/nextcloud/unsplash/assets/9658882/afe4e600-98a4-4841-bddd-0322c776feec)
_Changes made and saved._
![Refresh](https://github.com/nextcloud/unsplash/assets/9658882/24f1d471-9349-4666-954a-f2e69882ce33)
_Settings after refreshing page._

**Comment by BenH4** [comment] 2024-01-16 17:54
> > Not related @Raemsna. Issue is settings page does not work.
> 
> Perhaps related to this and the fix, I'm in NextCloud 28.0.1 and have enabled Splash. It works, but no modifications made in the settings (under Theming) save. It claims that it's saved, but then you refresh and everything has reset to default settings. Other changes made under Theming to non-Splash settings are saved correctly.
> 
> ![Changes](https://private-user-images.githubusercontent.com/9658882/293781149-afe4e600-98a4-4841-bddd-0322c776feec.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0Mjc5MTgsIm5iZiI6MTcwNTQyNzYxOCwicGF0aCI6Ii85NjU4ODgyLzI5Mzc4MTE0OS1hZmU0ZTYwMC05OGE0LTQ4NDEtYmRkZC0wMzIyYzc3NmZlZWMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMTc1MzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmQyYmM2NGQ1YjExMzBiNmJkNzliZWNjMGEwMGQ5Nzc2ODkwYjk2NzgwMmQ1MzU2NjM4NWU3Yjc2NzRlMmQ1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.a9zHnzjGkfBoqSwb6s7z_n5sxfCSMjrwDKZXIjYmI8Y) _Changes made and saved._ ![Refresh](https://private-user-images.githubusercontent.com/9658882/293781367-24f1d471-9349-4666-954a-f2e69882ce33.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0Mjc5MTgsIm5iZiI6MTcwNTQyNzYxOCwicGF0aCI6Ii85NjU4ODgyLzI5Mzc4MTM2Ny0yNGYxZDQ3MS05MzQ5LTQ2NjYtOTU0YS1mMmU2OTg4MmNlMzMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMTc1MzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWU5NDg1ZmI3ODU3Y2MwNTI3MGJkYzI1MDc3OGE2Y2VhNzA4YjlmZTRhZGU1N2ZjZDdiOGM2Y2RkZDEyY2NiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.b0oMExgD1PySkA_FZwKa2me7oFcJXp2aCDfj8K_mYX8) _Settings after refreshing page._
> 
> **Edit:** Just to add a bit more colour in case it's related and useful: ![Log](https://private-user-images.githubusercontent.com/9658882/293796935-03188f13-c8d0-4d5a-9d10-57ffcf26599a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0Mjc5MTgsIm5iZiI6MTcwNTQyNzYxOCwicGF0aCI6Ii85NjU4ODgyLzI5Mzc5NjkzNS0wMzE4OGYxMy1jOGQwLTRkNWEtOWQxMC01N2ZmY2YyNjU5OWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMTc1MzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGNkNjc2ZDgyNjJkOTlmZmNiNGM3OGJlZTQ3ZWI2NDdlMDA4MmNlNTViZTJlNmQxNTY2ZjQ1ZTQyZWZjMjBmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pMO1XgO7sZE3JLsvFqMlq2W6WN27lAYRBuxDsDX-Efc)

I am having the same issue on a fresh install of NC

**Comment by ChildLearningClub** [comment] 2024-01-17 04:22
This is by no means a fix, but will make it so that "Set random image as dashboard background" is on by default and should get the dashboard background working on 28.01. 

```
cd nextcloud/custom_apps/unsplash/lib/Services
sudo nano SettingsService.php
```
change line:
`        return $this->config->getAppValue($this->appName, self::STYLE_DASHBORAD, 0) == 1;`
to:
`        return $this->config->getAppValue($this->appName, self::STYLE_DASHBORAD, 1) == 1;`

**Comment by BenH4** [comment] 2024-01-18 14:01
> This is by no means a fix, but will make it so that "Set random image as dashboard background" is on by default and should get the dashboard background working on 28.01.
> 
> ```
> cd nextcloud/custom_apps/unsplash/lib/Services
> sudo nano SettingsService.php
> ```
> 
> change line: ` return $this->config->getAppValue($this->appName, self::STYLE_DASHBORAD, 0) == 1;` to: ` return $this->config->getAppValue($this->appName, self::STYLE_DASHBORAD, 1) == 1;`

Did the trick, not a fix indeed but thanks!!!

**Comment by jet438** [comment] 2024-01-21 16:48
Any update on this? I'm still waiting to update to NC28 but don't want to do so without Splash. too cool of an app.

**Comment by newhinton** [comment] 2024-01-21 20:43
I am infact working on support for 28. I have fixed most issues with the latest version, but i still have to test some new features. I couldnt spare much time for this project, so progress has been slow.

**Comment by SK-Crow** [comment] 2024-01-22 00:46
Noting that @ste7enm is correct with one of the issues on Hub 28, I'm getting the same error message in my logs.  Just commenting ot keep an eye on it.

**Comment by ste7enm** [comment] 2024-01-22 23:39
> Any update on this? I'm still waiting to update to NC28 but don't want to do so without Splash. too cool of an app.

I'll mention too that it **does work** in NC28 (in that you do get random images from Unsplash displayed as background images, as intended), it's just that you can't make changes to your settings (at least for me). So if you're cool with keywords "nature,nature" and not making any other tweaks, you could still update @jet438.

**Comment by SK-Crow** [comment] 2024-01-23 23:26
> > Any update on this? I'm still waiting to update to NC28 but don't want to do so without Splash. too cool of an app.
> 
> I'll mention too that it **does work** in NC28 (in that you do get random images from Unsplash displayed as background images, as intended), it's just that you can't make changes to your settings (at least for me). So if you're cool with keywords "nature,nature" and not making any other tweaks, you could still update @jet438.

I found that it doesn't function at all.  It doesn't break anything on my end, but both saving and splash login are not functioning.  It's like it's not there at all.  Just errors.

![image](https://github.com/nextcloud/unsplash/assets/1341176/269afb02-9b4e-4bd9-ba43-e7c7b210d03d)
![image](https://github.com/nextcloud/unsplash/assets/1341176/d4b88608-032e-4a92-a988-36759ff1b0b4)
![image](https://github.com/nextcloud/unsplash/assets/1341176/a17d21b4-8902-460d-898c-7d4fb14e8d71)

**Comment by ingsocdev** [comment] 2024-02-22 11:13
Hopefully this is still in progress 🤞 I really want to use this with NC 28. Nothing works right now for me with this.

**Comment by newhinton** [comment] 2024-02-22 16:06
> Hopefully this is still in progress 🤞 I really want to use this with NC 28. Nothing works right now for me with this.

Yes! I finally figured out why the images weren't loading anymore on the login-screens. Now i only have to add a small attribution-icon to the login-pages, and i should be good to go!

**Comment by newhinton** [comment] 2024-02-22 22:36
If you are willing, #133 contains an updated version of splash. It should work with 28, and it also provides a few bug fixes AND features, like image-caching and source attribution on the loginscreen!

![image](https://github.com/nextcloud/unsplash/assets/25279821/6a5d328a-700b-49e3-b6e0-5c1f19965b82)

It is currently in testing, so there might be bugs.

**Comment by ingsocdev** [comment] 2024-02-22 22:46
Let me see if I can give this version a try!

**Comment by crocobc** [comment] 2024-03-06 08:28
> If you are willing, #133 contains an updated version of splash. It should work with 28, and it also provides a few bug fixes AND features, like image-caching and source attribution on the loginscreen!
> It is currently in testing, so there might be bugs.

Hi there,

Working nice with this pull. (Nextlcoud 28.0.3)

Thank you

**Comment by theron29** [comment] 2024-03-17 15:24
Can this please be released into official Nextcloud store?
Thanks.

**Comment by jger3110** [comment] 2024-03-29 19:06
Too bad there is nothing happening here. The second app I use that needs to be removed because of the incompatibility. Waiting months and now even 5 minor NC versions for an update that somehow is only available by some pull (???) is just not worth it. Thanks for the time it lasted...

**Comment by newhinton** [comment] 2024-03-31 10:52
> Waiting months and now even 5 minor NC versions for an update that somehow is only available by some pull (???) is just not worth it. 

The good news is that instead of complaining that someone else is doing the work not fast enough for you, you could instead help out by either adding code or doing a review.


As long as i am not getting paid and using *my* free time, i will do changes when i want to do them.
As always: It will be done, when it will be done.

**Comment by jger3110** [comment] 2024-03-31 11:00
Please do as you please, nobody is urging you to do anything. But as with every product or service: if it is not reliably available people will stop using it. Just as it is your right to maintain it. Or not.
And please forgive me for expressing my opinion just as you expressed yours by stating what you want to do and what not.

**Comment by newhinton** [comment] 2024-03-31 11:17
I know that this release has taken quite a while. And i would really like to get it out, there is a lot of work and quite a few features in there. But time is limited, and it really isn't that useful to be told that it took that long.

This PR is feature complete, that means the basics are done. There are still a few things to work out before a release, as reported by the others in said PR. Once those are fixed, i will release it proper. Thank you for your understanding and patience.

**Comment by jger3110** [comment] 2024-03-31 11:22
Danke Felix, dieses Statusupdate ist hilfreich. *daumenhoch*

**Comment by waja** [comment] 2024-03-31 12:56
While working on compatibility for 28, you can already target 29, which is going to be released soon. ;)

**Comment by asheroto** [comment] 2024-04-23 22:44
Looks like Nextcloud 29 is being [released tomorrow](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule), April 24, 2024.

The end of life (security support) for Nextcloud 27 is in June 2024.

![image](https://github.com/nextcloud/unsplash/assets/49938263/ab09a05e-f77f-4732-8b16-bb5ef25d0268)

Any updates on these? 😊

**Comment by newhinton** [comment] 2024-04-24 08:36
@asheroto You can track the progress of 28 support over here: #133 

I have just updated some error handling regarding the unsplash api, if you are willing, testers are always welcome!

**Closed** 2024-07-16 11:11 UTC
Labels: bug

**Comment by monjurq** [comment] 2024-08-08 15:50
Nextcloud Version: 
Nextcloud Hub 8 (29.0.4)
Splash Version: 2.2.1
Background auto change isn't working. (it worked in the past)
No changes were made in the admin area under themes!!
PLEASE FIX IT, Thank You.
