### ISSUE TITLE
[NC20] [v. 1.2.0] Doesn't work anymore

### ISSUE THREAD

**Issue by Netsurfer70** [nextcloud/unsplash#82] opened 2021-01-19 07:49 UTC
Updated yesterday to 1.2.0 and had nice pictures again.

Today, same error as before.
Not changed or updated anything else.

**Comment by newhinton** [comment] 2021-01-19 12:11
This is very likely an duplicate of #72.

The issue is with the unsplash api, which is not really stable at the moment.

**Closed by newhinton** 2021-01-19 12:11 UTC
