### ISSUE TITLE
Undefined array key "Unsplash" at nextcloud/apps/unsplash/lib/ProviderHandler/ProviderDefinitions.php

### ISSUE THREAD

**Issue by gk26** [nextcloud/unsplash#147] opened 2024-09-13 06:30 UTC
use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

- [x] This is not a feature request
- [x] This is not an image-provider request
- [x] I have searched the issuetracker if the issue is not already reported.

**Describe the bug:**

`[PHP] Fehler: Undefined array key "Unsplash" at /var/www/nextcloud/apps/unsplash/lib/ProviderHandler/ProviderDefinitions.php#95
	GET /index.php/apps/files/preview-service-worker.js
	von 192.168.2.31 von xxx um 13.09.2024, 08:18:30
`

**To Reproduce:**
Error in _nextcloud.log_.
If _Splash_ app is disabled there is no error. If enabled, every Request causes an error

**Server:**
 - Nextcloud version: 29.0.7
 - Splash-App version: 3.0.1

**Comment by arsounet** [comment] 2024-09-19 08:34
I've got this issue using Side Menu app.

**Comment by gk26** [comment] 2024-09-27 07:13
With nextcloud Version [Nextcloud Hub 9] (30.0.0) ans Splash Version 3.0.1 for me it's "just" an error in the logfile.

**Comment by newhinton** [comment] 2024-09-27 07:25
The original "unsplash" integration was removed with 3.0.1. So its expected that it shows up as an error in the log, but that can easily be fixed by changing the provider via the ui. That resets the internal setting, and the provider will be stored properly. I'll check this with 3.0.0 on the weekend.

**Comment by gk26** [comment] 2024-09-27 09:04
Changeing the provider to "WallhavenCC" fixed it for me.

**Comment by immanuelfodor** [comment] 2024-10-02 18:56
Found this issue through NC 30 logs. Seems https://github.com/nextcloud/unsplash/issues/149 is a duplicate of this one.

I confirm, setting the provider from Unsplash to WallhavenCC solves the issue.

**Comment by newhinton** [comment] 2024-10-06 10:25
Closed by 3b7f803f

**Closed by newhinton** 2024-10-06 10:25 UTC
Labels: bug, Needs more Info
