### ISSUE TITLE
we coudnt find that photo

### ISSUE THREAD

**Issue by arathink** [nextcloud/unsplash#75] opened 2020-12-31 07:12 UTC
we coudnt find that photo

**Comment by arathink** [comment] 2020-12-31 07:14
we couldnt find that photo

**Comment by marius-wieschollek** [comment] 2020-12-31 09:35
Before you open a new issue, please check if there is already an existing issue about your problem.
If not, please provide all relevant information about the problem and how to reproduce it.
"we couldnt find that photo" is not helpful at all and if i didn't know that this issue is a duplicate of #72, i would have no clue at all what you're talking about.

**Closed by marius-wieschollek** 2020-12-31 09:35 UTC
