### ISSUE TITLE
NC20 Login screen cannot load picture

### ISSUE THREAD

**Issue by oswaldo-be** [nextcloud/unsplash#72] opened 2020-12-23 22:23 UTC
It says: We couldn't find that picture in big letters

**Comment by TartanPaintPot** [comment] 2020-12-24 09:10
I have a self hosted system, that's showing the same - "We couldn't find that picture"
Tried disabling/enabling to check, even removed and added again - still showing the same message.

All my users love the varying background pictures. Hopefully it's just a case of a referenced directory having moved, and can be repointed etc.

**Comment by marius-wieschollek** [comment] 2020-12-24 09:36
This seems to be an issue on the side of unsplash.
The provide an url that should redirect to a random image matching given search terms.
We use the url https://source.unsplash.com/featured/?nature to find images related to nature. This url always returns the not found error.
If another search term is added, the url works again, see: https://source.unsplash.com/featured/?nature,water

**Comment by JMoVS** [comment] 2020-12-24 14:45
Hi, if I click on your second link, it also doesn't work (I also face the issue #72 at my instance)

**Comment by chillriver** [comment] 2020-12-24 22:33
Hello together, in my case the second link works. Is there a way to change the term as workaround? I love this feature.

**Comment by marneu** [comment] 2020-12-25 09:17
Suggestion and just an Idea: Make it a bit more comfortable for example include a fixed table array with either date(s|ranges) like Christmas, Silvestre and other world wide valid special days a.s.o. and set a value in the array with corresponding keywords like _?Xmas_ etc.
Alternate would be to allow a personal setup keyword in user settings - or do both ... would be nice -> feature request?

**Comment by Ivar418** [comment] 2020-12-26 00:09
i also have the same issue for my self hosted nc server on my raspberry pi. it shows the no image found. also on the statusbar if enabled

**Comment by crewdk** [comment] 2020-12-26 12:01
> If another search term is added, the url works again, see: https://source.unsplash.com/featured/?nature,water

Thnx, this works for me. 

For all: you could just edit search terms in files: 

/apps/unsplash/css/header.css
/apps/unsplash/css/login.css

**Comment by meepmeep** [comment] 2020-12-27 10:51
It looks like the "nature" category doesn't work anymore.

From the unsplash website : https://source.unsplash.com

- If I try the https://source.unsplash.com/featured/?nature it always send an error.
- But https://source.unsplash.com/featured/?water doesn't 

So i modify files from https://github.com/nextcloud/unsplash/issues/72#issuecomment-751349184  to set : 
https://source.unsplash.com/featured/?wallpapers

(other category like "architecture" doesn't work either).
So the issue is on unsplash side ...

**Comment by TartanPaintPot** [comment] 2020-12-27 19:15
> I have a self hosted system, that's showing the same - "We couldn't find that picture"
> Tried disabling/enabling to check, even removed and added again - still showing the same message.
> 
> All my users love the varying background pictures. Hopefully it's just a case of a referenced directory having moved, and can be repointed etc.

OK, all fixed after I edited the 2 files in the following location:    /var/snap/nextcloud/current/nextcloud/extra-apps/unsplash/css/header.css & login.css

to have the following URL https://source.unsplash.com/featured/?nature,water  and all working again.

Hope this helps anyone else out - if you've installed NextCloud with snap, that is....

**Comment by chillriver** [comment] 2020-12-27 20:02
> > If another search term is added, the url works again, see: https://source.unsplash.com/featured/?nature,water
> 
> Thnx, this works for me.
> 
> For all: you could just edit search terms in files:
> 
> /apps/unsplash/css/header.css
> /apps/unsplash/css/login.css

This workaround works well for me. Thanks.

**Comment by thilojaeggi** [comment] 2020-12-28 01:01
Using https://source.unsplash.com/featured/?nature,nature works too.

**Comment by Ivar418** [comment] 2020-12-28 02:32
> Using https://source.unsplash.com/featured/?nature,nature works too.

That makes so little sense that it does. Funny😂

**Comment by marneu** [comment] 2020-12-28 10:55
@meepmeep: https://source.unsplash.com/featured/?architectural works too. (architecture!=architectural)
But this is this the time for ?silvester ;)

**Comment by Superyorch** [comment] 2020-12-29 18:18
I have modified both files (header and login) and added water at the end, nature again, architectural and still in all cases receiving the same error. For some reason it seems as if it is not even bothering to check the url saved in those files.

**Comment by newhinton** [comment] 2020-12-29 19:27
I will fix that, but it will probably take me some time since i am currently fixing my own nextcloud. i hope that i can get an update out around new year's eve, with the improvement suggested by @marius-wieschollek

**Comment by Superyorch** [comment] 2020-12-30 15:20
thank you! After fiddling around with other tokens like: water, tech, wallpapers, architecture, etc they all seem to work perfectly and the only broken one is nature. Hope that helps narrow it down to the culprit. Happy new year!

**Comment by Valdnet** [comment] 2020-12-30 22:06
I propose to add the link change function from the Administrator Panel :grin:.

**Comment by Valdnet** [comment] 2021-01-03 11:31
@newhinton The solution in PR # 76 does not fix the bug. After a few views of the NC page, the message "We couldn't find that photo" is displayed again.

**Comment by wilfreddijksman** [comment] 2021-01-03 12:14
The url https://source.unsplash.com/featured/nature works for me (without the question mark).

**Comment by Valdnet** [comment] 2021-01-03 16:03
@wilfreddijksman The link without a question mark displays images from different groups (not only from nature).

**Comment by marius-wieschollek** [comment] 2021-01-03 16:45
I can confirm that my PR does no longer fix the issue. Also https://source.unsplash.com/featured/?nature,water does return images that clearly don't match (like fireworks)

The api seems to be really broken right now

**Comment by Corum92** [comment] 2021-01-05 11:02
Thanks for fixing this (if done actively).  Works again on my end with lovely pictures from oranges, nature et al.  Cheers!

**Comment by newhinton** [comment] 2021-01-05 11:17
We didnt really do anything, but it seems that the issue was not on our end. For the future i will have to update the app to easily switch categories, so that this will not happen again

**Comment by tom-ch1** [comment] 2021-01-06 18:18
`https://source.unsplash.com/1920x1080/?nature,,` seem to work (...right now, for me... ;-) )

**Comment by Corum92** [comment] 2021-01-06 21:55
> 
> 
> Thanks for fixing this (if done actively). Works again on my end with lovely pictures from oranges, nature et al. Cheers!

And gone again.  Error message is back on ...  Maybe it is a slack joint @unsplash ;-)

**Comment by armaccloud** [comment] 2021-01-09 10:01
I had contact with Unspash Support; apparently the source.unsplash.com URL is not supported anymore.
I think this requires a structural change in the unsplash app.

![image](https://user-images.githubusercontent.com/9272078/104088818-e01d6a80-5269-11eb-9dba-94cad192a5b3.png)

**Comment by newhinton** [comment] 2021-01-09 10:06
that is good to know! thanks for sharing this with us.
I already have some baseline work for other imageprovider, so i'll have to finish those rather soon :D

**Comment by newhinton** [comment] 2022-05-01 18:27
I will close this issue since it seems resolved. The fact that the original unsplash api is unsupported will be handled in a different pr when it comes to that.

**Closed by newhinton** 2022-05-01 18:27 UTC

**Comment by froman753** [comment] 2023-06-28 20:07
I'm currently running into this issue. Has there been any progress on migrating to the new API in the last 14 months?
